### ISSUE TITLE
Pre-Release - wheel testing (C64)

### ISSUE THREAD

**Issue by kbx0** [willyvmm/mouSTer#11]
I have an Ultimate64 Elite with 2 SIDs.

I have tested the latest pre-release mouster update with 2 wireless mice and 1 wireless mouse in mousetester2.

Sorry to say that middle click and wheel do not work at all. Tried lots of times now.

I also have the MicroMYS 5, with the wired ps/2 to usb mouse, the middle click and wheel works in mousetester2, but who wants to use a wired mouse?

Not sure if it should be functioning but if you need testers I'd love to help.

**Comment by willyvmm** [comment]
#9

**Comment by gnacu** [comment]
I have just completed Wheel support at a low-level in the C64 OS KERNAL and UI Toolkit, with a driver for MicroMys and updates to the Mouse settings Utility to adjust direction and sensitivity. If you guys release support for mouse wheel for MouSTer, I promise I'll write a MouSTer driver for C64 OS immediately. Mouse Wheel support rolls out for C64 OS very soon, in the next update, v1.02.

**Comment by willyvmm** [comment]
Please try the latest firmware: https://github.com/willyvmm/mouSTer/releases/tag/3.17.3377

**Comment by markusC64** [comment]
I confirm the lastest firmware 3.17.3377 works on Ultimate 64 with wired mouse. Full Micromys functionality verified - incl. all 3 buttons and wheel.

**Comment by willyvmm** [comment]
As the C1351 have been rebuild once again, please try the latest build:  https://github.com/willyvmm/mouSTer/releases/tag/3.17.3455

**Comment by gnacu** [comment]
Sorry for the late response, I just tested this latest firmware, and it works perfectly, as far as I can tell. I tested the mouse wheel in C64 OS and it's working great.

Greg.

**Comment by kbx0** [comment]
Sorry for the delay in responding.

Tested:  Logitech M525 Wireless - Razer Deathadder V2 Pro Wireless

Machine: Ultimate64 Elite on 3.10c with Dual Arm2Sid.

Software: Joyride 1.6

Results: Three working buttons and a working scroll wheel.

Thank you so much, you've made the Mouster so useful.
