### ISSUE TITLE
Question: Mouster Hot-Swap on C64/128 ?!?

### ISSUE THREAD

**Issue by lovrenco** [willyvmm/mouSTer#12]
I suppose this is not possible without the rick of damaging machine? Am I correct?

To explain, pluging in or out the adapter while computer is turned on.

**Comment by willyvmm** [comment]
Don't do that.
This is not a matter of mouSTer itself, rather the architecture of C64. 
The mouSTer is designed to minimalize the risk of hotplugging, but due to C64 architecture (and any other old computer) it's not supported.
The risk lies on the HOST side.
The MouSTer will survive.
