### ISSUE TITLE
THEC64Joystick or THEA500Gamepad not working

### ISSUE THREAD

**Issue by Schwefelholz** [willyvmm/mouSTer#18]
I cannot get THEC64Joystick or THEA500Gamepad working with mouSTer. Debug files attached.

Thanks for looking into this...

[MOUSTER.DBG.zip](https://github.com/willyvmm/mouSTer/files/8481429/MOUSTER.DBG.zip)

**Comment by willyvmm** [comment]
Same issue as #6

**Comment by willyvmm** [comment]
Please try the latest Pre-Release Firmware: https://github.com/willyvmm/mouSTer/releases/tag/3.17.3309
