### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by TomCat666** [willyvmm/mouSTer#19]
Bught a few  mouSTer adapters because it had support for amiga mouse, cd32 pad and 1351 mouse on c64. But now it seems two of those have glitches that make them not really usable, only normal amiga mouse and 2 button joystick are working flawlessly. It has been more than 5 months since any update or anything. :( Hope the author is well and the project is not dead and forgotten.

**Comment by kbx0** [comment]
She's dead Jim :(

**Comment by willyvmm** [comment]
[#23 ](https://github.com/willyvmm/mouSTer/issues/23#issue-1500949553)

**Comment by willyvmm** [comment]
https://github.com/willyvmm/mouSTer/issues/23#issue-1500949553
