### ISSUE TITLE
Only one button supported for C64 mouse

### ISSUE THREAD

**Issue by ssuukk** [willyvmm/mouSTer#2]
The Portal game on C64 requires two mouse buttons, one is for blue portal, another for pink. It seems mouSTer supports only one mouse button in C64 mode, though!

**Comment by willyvmm** [comment]
It's included in the new upcoming version.

**Comment by willyvmm** [comment]
Try this Firmware:  https://we.tl/t-NqNx1OknEs

**Comment by ssuukk** [comment]
I don't remember how to update the fw, but if it is enough to put it in the root of some SD drive and turn mouster on, then it didn't help (or didn't update).

**Comment by radius75** [comment]
@ssuukk 
Clean the flash drive.
Create a MOUSTER folder
Put the FW file in the folder.
Plug in the Mouster with a flash drive and power the C64
Wait a minute.
Delete the FW file from the flash drive.
Plug it back in and power up the C64
Check the FW version in the automatically created INI file.

**Comment by ssuukk** [comment]
działa

wt., 31 sty 2023, 09:38 użytkownik radius75 ***@***.***>
napisał:

**Comment by willyvmm** [comment]
Thanks for Feedback.
