### ISSUE TITLE
Mouster cd32 joypad emulation doesnt work correctly in some games

### ISSUE THREAD

**Issue by moulder625** [willyvmm/mouSTer#24]
Hi,

I have dual shock 4 connected to Mouster with cd32 joypad emulation on. In some games adapter is't working correctly. For example in Flashback unnoficial cd32 port joypad is clicking buttons on its own when splashscreen with language and difficulty selection is shown. Also in Skeleton Crew after few seconds game exits to main menu because mouster is emulating back button click on its own. Are you planning to release new firmware with bug fixes?

**Comment by willyvmm** [comment]
#8

**Comment by willyvmm** [comment]
Please try this firmware: https://github.com/willyvmm/mouSTer/releases/tag/3.17.3222

**Comment by moulder625** [comment]
Ok,.Will do.that.

Thanks.and.regards,
Tomasz

W 25 stycznia 2023 23:42:28 willyvmm ***@***.***> napisał:

**Comment by TomCat666** [comment]
Working fine for me, tried several games that support cd32 pad and workbench tools that display cd32 button activity. No more ghost (or wrong) button presses. Thanx!

**Comment by willyvmm** [comment]
Thanks for Feedback.

**Comment by moulder625** [comment]
Ok, so I've tried newest beta firmware and there is progress for example Skeleton Crew is working correctly without wrongly pressed buttons.
 But Flashback unnoficial port for CD32 with cd32 joypad support is not working correctly - mouster is pressing buttons on itself on few splashscreens where there are options to choose start level, difficulty, language and so on.
