### ISSUE TITLE
PS2 TO PC Gamepad Converter is not working

### ISSUE THREAD

**Issue by Jumpman64** [willyvmm/mouSTer#3]
Hi there,

i tried this adapter: https://www.speedlink.com/PS2-TO-PC-Gamepad-Converter/SL-6502-SBK
MouSTer does not recognise it and keeps blinking.

The "Analog" LED on the PS2 controller is responding when pressing the Analog button, so at least there's power. :)

Here's the debug data:
[MOUSTER.DBG.TXT](https://github.com/willyvmm/mouSTer/files/7633560/MOUSTER.DBG.TXT)

Thanks for the support, MouSTer is awesome.

**Comment by willyvmm** [comment]
Please try the latest Pre-Release Firmware: https://github.com/willyvmm/mouSTer/releases/tag/3.17.3309

**Comment by Jumpman64** [comment]
PS2 to PC Converter tested with MouSTer FW Version 3.17.3377 - it works!

**Comment by Jumpman64** [comment]
Just for documentation, if someone else is using this PS2 to PC adapter too: :)
The analogue stick needs a remap.
With the default mouster.ini: Dpad is correctly assigned
but the right A-stick of the PS2 controller is used and directions are:
```
  L
U + D
  R
```
triangle/circle: fire
square/X: auto fire
