### ISSUE TITLE
TRUST GXT 1230 Muta do Switch / PC

### ISSUE THREAD

**Issue by kokisek** [willyvmm/mouSTer#34]
Very Please add support for the gamepad model BLUETOOTH CONTROLLER FOR PC AND SWITCH
 trust GXT 1230 MUTA

https://mediamarkt.pl/komputery-i-tablety/kontroler-bezprzewodowy-trust-gxt-1230-muta-do-switch-pc?gclid=Cj0KCQjw7aqkBhDPARIsAKGa0oKcwD3sfEKdd16ahxa-NO3KrmqiCqf1PSXDevX0s4TjeGwjh8QOqB8aAsbDEALw_wcB&gclsrc=aw.ds

The gamepad has its own USB RF receiver.
Will you be able to do it before the holidays? After meeting your uncle from Poland ;-)?

**Comment by willyvmm** [comment]
Please attach the DEBUG file.
