### ISSUE TITLE
C64: Question about 3xFire Joy 

### ISSUE THREAD

**Issue by radius75** [willyvmm/mouSTer#5]
![Z1hsJ2](https://user-images.githubusercontent.com/1929111/147492861-4dbd58ea-cbd1-4dc1-99ab-5922c2d8a884.png)
It is possible to setup a mouster to have a C64Joy 3xFire with a PC Joypad
Any sugestion for configuration?
Thanks

**Comment by radius75** [comment]
It's already working for me.
I set the buttons like this.
Maybe it will be useful to someone. (do not close thread)

For standard PC XBOX360 Gamepad

A = Fire1
B = Fire2 (potx)
X = Fire3 (poty)
Y = AutoFire1

```
[mouster]
mode=gpad
[gamepad]
number=00
revpotlines=true
gbutton01=mb
gbutton02=fire
gbutton03=rb
gbutton04=*fire
gbutton05=none
gbutton06=none
gbutton07=none
gbutton08=none
gbutton09=none
gbutton10=none
gbutton11=none
gbutton12=none
gbutton13=none
gbutton14=none
gbutton15=none
gbutton16=none
```

**Comment by willyvmm** [comment]
That's the correct attempt to have 3 buttons working on most 8/16 bit machines.

**Comment by radius75** [comment]
There is a problem with reading potX and potY in gpad mode.
To run them at all, you must first mouse and then gpad in ini file.

Reproduction step:

- run c64 + mouster
- insert pendrive, ini mode = mouse, 1351
- power off, unplug pendrive
- power on, test mouse ok
- insert pendrive mode = gpad
- 3xbutton joy works now on gamepad

If we do power on / off now, fire2 and fire3 stop working.
You have to repeat the whole procedure from the beginning.
Otherwise I can't get mouSTer to make this work.

**Comment by Jumpman64** [comment]
Would be really nice to have three buttons for supported games. 
Tried this setup for the first time. It still didn't work with these gamepad settings in firmware 3.17.3377:
mode=gpad
revpotlines=true
gbutton01=mb
gbutton02=fire
gbutton03=rb
gbutton04=*fire

i'm using a DS4 controller + 8bitdo wireless adapter. 
X works as fire, triangle as auto fire. Square and circle do nothing.
Tested with [Joyride 1.6 ](https://csdb.dk/release/?id=219494) on an U64

**Comment by radius75** [comment]
With FW 3.17.3377 I couldn't get Fire 2 and 3 to work either.
C64c

**Comment by willyvmm** [comment]
Hi. 
Please try the latest firmware: https://github.com/willyvmm/mouSTer/releases/tag/3.17.3470
This option has been removed by me by mistake and is restored in this build.

**Comment by radius75** [comment]
Fire 2 i 3 (potx i poty) działają poprawnie, a oba te przyciski działają nadal nawet po zrobieniu restartu zasilania.

Przydało by się żeby Mouster sam wykonywał reboot zaraz po zaczytaniu configu z INI. (bez zrobienia tego, załadowana konfiguracja nie uruchomi się) Oszczędzi to często czas na wyłączanie zasilania C64 a często wgrywanie programu/gry od nowa.
--
Fire 2 and 3 (potx and pots) work fine and both of these buttons still work even after doing a power reboot.

It would be useful for Mouster to reboot itself right after reading the config from INI. (without doing this, the loaded configuration will not start) This will often save time for turning off the C64's power and often reloading the program / game.

**Comment by radius75** [comment]
Jeśli nie stworzy to nowego problemu, nieskończonej pętli ładowania INI i Restartu.
Może jeśli się da to restart np zawsze po usunięciu pendrive USB

--
If it doesn't create a new problem, infinite INI load loop and Restart.
Maybe if it is possible to restart, e.g. always after removing the USB flash drive

**Comment by radius75** [comment]
Bug naprawiony, wątek do zamknięcia.

--
Bug fixed, thread to be closed.

**Comment by willyvmm** [comment]
> If it doesn't create a new problem, infinite INI load loop and Restart.
> Maybe if it is possible to restart, e.g. always after removing the USB flash drive

Best ideas are the simplest and most difficult to find.
I struggled with this issue for a really long time, and could not find any good solution. But the solution is so simple :)
Thanks for the Idea. It is implemented in the latest Pre-Release 3.17.3475 https://github.com/willyvmm/mouSTer/releases/tag/3.17.3475

**Comment by Jumpman64** [comment]
tested mouSTer.fw.3.17.3475  - Mario is a blast with 2nd button mapped to square on a PS4 pad.
Great work!

**Comment by willyvmm** [comment]
Thanks for the feedback.
