### ISSUE TITLE
Issue with wireless USB NES controller (Debug info included)

### ISSUE THREAD

**Issue by CommodoreKevin** [willyvmm/mouSTer#7]
I bought a new NES style wireless USB controller, and it was not working, here's the debug info:

[MOUSTER DEBUG.txt](https://github.com/willyvmm/mouSTer/files/7818748/MOUSTER.DEBUG.txt)

**Comment by willyvmm** [comment]
Please try the latest Pre-Release Firmware: https://github.com/willyvmm/mouSTer/releases/tag/3.17.3309
